### ISSUE TITLE
Wierd results from get_match_history_by_seq_num()

### ISSUE THREAD

**Issue by ssrebelious** [joshuaduffy/dota2api#57]
I expect to get matches like `2907738537`, `2907738538`, `2907738539` (or close to that) starting with the match id `2907738536` ([a very recent match](https://www.dotabuff.com/matches/2907738536)):
```
all_pick = api.get_match_history_by_seq_num(
                                            game_mode=22,
                                            start_at_match_seq_number=2907738536,
                                            matches_requested=3
                                            )
for m in all_pick['matches']:
    print(m['match_id'], '||', timestamp_to_human_time(m['start_time']))
```
But I get very old data from this request:
```
496 || 2011-03-03 06:04:49 
497 || 2011-03-03 06:44:24 
499 || 2011-03-03 10:13:33
```
What is wrong with my request?

**Comment by evaldobratti** [comment]
The parameter `start_at_match_seq_number` refers to `match_seq_num` from matches, and not `match_id`, as you requested.
To get newer matches than your 2907738536, you must request with 2536306300, this one being `match_seq_num` of the 2907738536 `match_id`.

`match_seq_num` is another sequence, I think that `match_id` is set when a game is started and `match_seq_num` when it ends, but there is no info about it.

Since they are different, do not expect sequential `match_id`'s when using `match_history_by_seq_num` end point.

**Comment by ssrebelious** [comment]
Thanks for the clarification, but nothing has changed from the outcome point of view. I still get the exact same result with `start_at_match_seq_number = 2536306300` as with `start_at_match_seq_number = 2907738536` and if I don't provide `start_at_match_seq_number` at all I get the same result. It looks like `start_at_match_seq_number` parameter is being ignored entirely. `Pyhton 3.4.5`, `dota2api 1.3.2`.

**Comment by ssrebelious** [comment]
My bad, used `start_at_match_seq_number` instead of `start_at_match_seq_num`. Sorry for bothering Thanks for clarification though!
